/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2026-08-04 23:02:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mantenUsuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Registrar Usuario</title>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"shell\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("    <div class=\"page-head\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <h1>Registro de Nuevo Usuario</h1>\r\n");
      out.write("        <p class=\"subtitle\">Crea una nueva cuenta de acceso al sistema</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"UsuarioServlet?tipo=lis\" class=\"btn btn-sm\">Ver listado</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

        String mensaje = (String) request.getAttribute("mensaje");
        String tipoMsg = (mensaje != null && mensaje.contains("correctamente")) ? "ok" : "error";
    
      out.write("\r\n");
      out.write("    ");
 if(mensaje != null){ 
      out.write("\r\n");
      out.write("      <div class=\"toast ");
      out.print( tipoMsg );
      out.write('"');
      out.write('>');
      out.print( mensaje );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <h2>Datos del usuario</h2>\r\n");
      out.write("      <form action=\"UsuarioServlet?tipo=regis\" method=\"POST\" novalidate>\r\n");
      out.write("        <div class=\"grid cols-2\">\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Código</span>\r\n");
      out.write("            <input type=\"text\" id=\"txtCod\" name=\"txtCod\" required placeholder=\"Ej: U001\">\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Usuario</span>\r\n");
      out.write("            <input type=\"text\" id=\"txtUsuario\" name=\"txtUsuario\" required placeholder=\"Nombre de usuario\">\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Contraseña</span>\r\n");
      out.write("            <input type=\"password\" id=\"txtPassword\" name=\"txtPassword\" required placeholder=\"••••••••\">\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Rol</span>\r\n");
      out.write("            <select id=\"rol\" name=\"rol\" required>\r\n");
      out.write("              <option value=\"\">Seleccione un rol...</option>\r\n");
      out.write("              <option value=\"1\">Administrador</option>\r\n");
      out.write("              <option value=\"2\">Técnico</option>\r\n");
      out.write("              <option value=\"3\">Recepcionista/Cajero</option>\r\n");
      out.write("               \r\n");
      out.write("            </select>\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>¿Es empleado?</span>\r\n");
      out.write("            <select id=\"cboEmpleado\" name=\"cboEmpleado\" required>\r\n");
      out.write("              <option value=\"true\">Sí</option>\r\n");
      out.write("              <option value=\"false\" selected>No</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Estado</span>\r\n");
      out.write("            <select id=\"cboEstado\" name=\"cboEstado\" required>\r\n");
      out.write("              <option value=\"true\" selected>Activo</option>\r\n");
      out.write("              <option value=\"false\">Inactivo</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Apellidos</span>\r\n");
      out.write("            <input type=\"text\" id=\"txtApellidos\" name=\"txtApellidos\" required>\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Nombres</span>\r\n");
      out.write("            <input type=\"text\" id=\"txtNombres\" name=\"txtNombres\" required>\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Fecha de nacimiento</span>\r\n");
      out.write("            <input type=\"date\" id=\"txtFechaNac\" name=\"txtFechaNac\" required>\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Celular</span>\r\n");
      out.write("            <input type=\"text\" id=\"txtCelular\" name=\"txtCelular\" placeholder=\"Ej: 987654321\">\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Correo electrónico</span>\r\n");
      out.write("            <input type=\"email\" id=\"txtCorreo\" name=\"txtCorreo\" required placeholder=\"correo@ejemplo.com\">\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <label class=\"field\">\r\n");
      out.write("            <span>Salario</span>\r\n");
      out.write("            <input type=\"number\" step=\"0.01\" id=\"txtSalario\" name=\"txtSalario\" required placeholder=\"0.00\">\r\n");
      out.write("          </label>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"field full\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-amber\">Registrar usuario</button>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
