/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2026-08-01 01:34:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.modulos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mantenUsuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Registrar Usuario</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 30px; background-color: #f4f7f6; }\r\n");
      out.write("        .form-container { background: #ffffff; padding: 25px; border-radius: 8px; max-width: 600px; box-shadow: 0px 0px 10px rgba(0,0,0,0.1); }\r\n");
      out.write("        .form-group { margin-bottom: 15px; }\r\n");
      out.write("        .form-group label { display: block; margin-bottom: 5px; font-weight: bold; color: #333; }\r\n");
      out.write("        .form-group input, .form-group select { width: 100%; padding: 8px; box-sizing: border-box; border: 1px solid #ccc; border-radius: 4px; }\r\n");
      out.write("        .btn-submit { background-color: #007bff; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; width: 100%; }\r\n");
      out.write("        .btn-submit:hover { background-color: #0056b3; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-container\">\r\n");
      out.write("    <h2>Registro de Nuevo Usuario</h2>\r\n");
      out.write("    \r\n");
      out.write("    <!-- El action debe apuntar a la ruta o mapeo de tu Servlet encargado de procesar el registro -->\r\n");
      out.write("    <form action=\"");
      out.print(request.getContextPath());
      out.write("/UsuarioServlet?tipo=regis\" method=\"POST\" >\r\n");
      out.write("    \r\n");
      out.write("        <!-- Código -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtCod\">Código:</label>\r\n");
      out.write("            <input type=\"text\" id=\"txtCod\" name=\"txtCod\" required placeholder=\"Ej: U001\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Usuario -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtUsuario\">Usuario:</label>\r\n");
      out.write("            <input type=\"text\" id=\"txtUsuario\" name=\"txtUsuario\" required placeholder=\"Nombre de usuario\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Password -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtPassword\">Contraseña:</label>\r\n");
      out.write("            <input type=\"password\" id=\"txtPassword\" name=\"txtPassword\" required placeholder=\"********\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Rol (id_rol) -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"rol\">Rol:</label>\r\n");
      out.write("            <select id=\"rol\" name=\"rol\" required>\r\n");
      out.write("                <option value=\"\">Seleccione un rol...</option>\r\n");
      out.write("                <option value=\"1\">Administrador</option>\r\n");
      out.write("                <option value=\"2\">Empleado</option>\r\n");
      out.write("                <option value=\"3\">Cliente</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Empleado (cboEmpleado) -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"cboEmpleado\">¿Es Empleado?</label>\r\n");
      out.write("            <select id=\"cboEmpleado\" name=\"cboEmpleado\" required>\r\n");
      out.write("                <option value=\"true\">Sí</option>\r\n");
      out.write("                <option value=\"false\" selected>No</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Apellidos -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtApellidos\">Apellidos:</label>\r\n");
      out.write("            <input type=\"text\" id=\"txtApellidos\" name=\"txtApellidos\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Nombres -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtNombres\">Nombres:</label>\r\n");
      out.write("            <input type=\"text\" id=\"txtNombres\" name=\"txtNombres\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Fecha de Nacimiento (txtFechaNac) -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtFechaNac\">Fecha de Nacimiento:</label>\r\n");
      out.write("            <input type=\"date\" id=\"txtFechaNac\" name=\"txtFechaNac\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Celular -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtCelular\">Celular:</label>\r\n");
      out.write("            <input type=\"text\" id=\"txtCelular\" name=\"txtCelular\" placeholder=\"Ej: 987654321\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Correo -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtCorreo\">Correo Electrónico:</label>\r\n");
      out.write("            <input type=\"email\" id=\"txtCorreo\" name=\"txtCorreo\" required placeholder=\"correo@ejemplo.com\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Salario -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"txtSalario\">Salario:</label>\r\n");
      out.write("            <input type=\"number\" step=\"0.01\" id=\"txtSalario\" name=\"txtSalario\" required placeholder=\"0.00\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Estado (cboEstado) -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"cboEstado\">Estado:</label>\r\n");
      out.write("            <select id=\"cboEstado\" name=\"cboEstado\" required>\r\n");
      out.write("                <option value=\"true\" selected>Activo</option>\r\n");
      out.write("                <option value=\"false\">Inactivo</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Botón de envío -->\r\n");
      out.write("        <button type=\"submit\" class=\"btn-submit\">Registrar Usuario</button>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
